version: 2

sources:
  - name: raw
    database: FOOD
    schema: RAW
    tables:
      - name: products
        identifier: PRODUCTS_RAW
        description: Raw product data from OpenFoodFacts API loaded from S3
        columns:
          - name: id
            description: Product ID
          - name: code
            description: Product barcode code
          - name: product_name
            description: Product name
          - name: brands
            description: Product brands (comma-separated)
          - name: countries
            description: Product countries (comma-separated)
          - name: categories
            description: Product categories (comma-separated)
          - name: ingredients_text
            description: Ingredients list
          - name: nutriscore_grade
            description: Nutriscore grade (A-E)
          - name: energy_100g
            description: Energy in kcal per 100g
          - name: sugars_100g
            description: Sugar content in grams per 100g

models:
  - name: stg_products
    description: Cleaned and normalized products
    columns:
      - name: id
        description: Product ID (primary key)
        tests:
          - unique
          - not_null
      - name: code
        description: Product barcode code
      - name: product_name
        description: Product name
      - name: nutriscore_grade
        description: Nutriscore grade (uppercase)

  - name: stg_brands
    description: Exploded brands from products
    columns:
      - name: brand_name
        description: Brand name
        tests:
          - not_null

  - name: stg_categories
    description: Exploded categories from products
    columns:
      - name: category_name
        description: Category name
        tests:
          - not_null

  - name: stg_countries
    description: Exploded countries from products
    columns:
      - name: country_code
        description: Country code
        tests:
          - not_null
